pub mod document_processor;
pub mod text_extractor;
pub mod chunker;
pub mod ocr_processor;
pub mod audio_processor;
pub mod llm_manager;
pub mod model_downloader;
pub mod embedding_manager;
pub mod hybrid_search;
pub mod clip_processor;
pub mod screenshot_processor;
pub mod query_intent;
pub mod advanced_query_processor;
pub mod boolean_query_parser;
pub mod boolean_query_executor;
pub mod intelligent_query_processor;
pub mod cached_query_classifier;
pub mod ranking;
pub mod result_processing;
pub mod user_intelligence;
pub mod search_suggestions;
pub mod preference_learning;
pub mod session_management;
pub mod contextual_search_engine;
pub mod adaptive_learning_engine;
// pub mod search_engine;
// pub mod indexer;
// pub mod embeddings;
// pub mod storage;